spring:
  application:
    name: ms-reservation-service

  datasource: #-Configuracoes do Banco de Dados
    url: jdbc:mysql://localhost:3306/ms-reservation?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: koatay108

  flyway:
    locations: classpath:db/migration #-Diretorio de scripts Flyway
    enabled: true #-Habilita o Flyway para aplicar migracoes
    baselineOnMigrate: true #-Adiciona e habilita a tabela de controle de historico de versoes do BD

  rabbitmq: #-Configuracoes minimas do RabbitMQ
    host: localhost
    port: 5672
    username: admin
    password: 123456

server:
  port: 8083

eureka:
  instance: #-Definindo um nome unico para cada instancia (ms-reservation-service : nome-da-instancia)
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

mq:
  queues:
    recieve-reservation: recieve-resertation