spring:
  application:
    name: ms-comparison-service

  datasource:
    url: jdbc:mysql://localhost:3306/dbcomparison_service?createDatabaseIfNotExist=true
    username: root
    password: koatay108

  flyway:
    locations: classpath:db/migration #-Diretorio de scripts Flyway
    enabled: true #-Habilita o Flyway para aplicar migracoes
    baselineOnMigrate: true #-Adiciona e habilita a tabela de controle de historico de versoes do BD

  messages: #-Configura o messages.properties
    basename: messages
    encoding: UTF-8

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
