spring:
  application:
    name: ms-notification-service

  rabbitmq: #-Configuracoes de conexao com broker
    host: localhost
    port: 5672
    username: admin
    password: 123456

  datasource: #-Configuracoes do Banco de Dados
    url: jdbc:mysql://localhost:3306/ms-notification?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: koatay108
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations: classpath:db/migration #-Diretorio de scripts Flyway
    enabled: true #-Habilita o Flyway para aplicar migracoes
    baselineOnMigrate: true #-Adiciona e habilita a tabela de controle de historico de versoes do BD

server:
  port: 8084

eureka:
  instance: #-Definindo um nome unico para cada instancia (ms-reservation-service : nome-da-instancia)
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

mq: #-Configuracoes de conexao com a fila
  queue:
    receive-reservation: receive-reservation



